### ISSUE TITLE
pdf的模型文件如何生成

### ISSUE THREAD

**Issue by jiying2007** [magicpdf/Magic-PDF#109]
您好，请问一下pdf的模型文件如何生成，我这边有使用开源的DocXChain，同一文件对比demo的生成效果相差很多，谢谢

**Comment by myhloli** [comment]
感谢关注我们的项目，这个仓库暂时只有模型后处理的pipeline，其他模块代码需要视开发进度后续放出

**Comment by myhloli** [comment]
> 您好，请问一下pdf的模型文件如何生成，我这边有使用开源的DocXChain，同一文件对比demo的生成效果相差很多，谢谢

目前版本已经内嵌了paddleocr的版面分析模型ppstructurev2，可以用来测试pdf解析效果，目前高精度模型由于配置环境复杂暂不放出。

**Comment by myhloli** [comment]
高精度模型解析工程也已经开源了，仓库地址https://github.com/opendatalab/PDF-Extract-Kit
近期会将高精度模型解析功能集成进mineru主仓库中，感谢您的关注。
